name: PR Checks

on:
  pull_request:
    branches: [main, develop]

env:
  NODE_VERSION: "20"

jobs:
  quick-checks:
    name: Quick PR Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run TypeScript check
        run: npx tsc --noEmit

      - name: Build application
        run: npm run build

      - name: Run Playwright tests (Chromium only)
        run: npx playwright test --project=chromium
        env:
          START_SERVER: true
          DEV_COMMAND: "npm run start"
